### ISSUE TITLE
Resources & Schedule are both here — should they be separated?

### ISSUE THREAD

**Issue by bjornmeansbear** [GD399-OSD/resources-readings#3]
Thinking that maybe we have a schedule and class plan repo, and then this is just for terms, resources, links, etc.? Any opinions from the team?

**Comment by devinhalladay** [comment]
Yeah I think this is a good idea. Keeping resources in the same repo as the
syllabus stuff might get unwieldy very quickly.

**Comment by bjornmeansbear** [comment]
@devinhalladay great, this is a good thing to do in class Friday then. A) show people how issue queues work? like how to file and issue, etc. And then we can also do a "create a new repo" and think about how to organize and evolve things together!

**Comment by devinhalladay** [comment]
I like that structure @bjornmeansbear. Might also be good to tangentially discuss how modes of making/thinking enabled by Git and GitHub can be brought to different design processes/different media.

e.g. maybe these could be some valuable questions to pose:
1. What ways can designers contribute to open source software? Can we actually help with any visual artifacts like UI without knowing how to implement changes in code? Can just the act of filing issues and asking questions provide something valuable?
2. Is it valuable to think about design process the same way engineers/devs think about the engineering process (i.e. minor versioning, version control, issues, milestones, PRs, etc etc)? Or does design (esp. in open-source contexts and mentalities) require a different way of thinking about process in order to be effective?
3. Do designers even need to produce visual artifacts to be considered designers? i.e. as a designer at Quora most of my job involved a combination of writing code and looking at metrics/formulating hypotheses/testing hypotheses/writing documents about product mechanics and user behavior. Maybe designers can help out in open source, or bring open source philosophies to design, by considering design as a more open and inclusive mode of thinking than it has been historically? Or, better yet, can being a designer without contributing actual design artifacts/aesthetic cues perhaps be *more* valuable than visual artifacts in certain contexts?
4. What are some differences between the open source community and the design community? Can we even call the design community a "community" when it's compared to the open source community?

**Comment by devinhalladay** [comment]
^^ I know all those questions are off-topic for this issue, but wanted to pose them in the context of your previous comment

**Comment by devinhalladay** [comment]
Er, it just occurred to me that I should've saved moving the schedule till Friday. Ooops! I'm gonna revert and delete my new repo. Sorry.

**Comment by devinhalladay** [comment]
Ok, fixed it. My bad.

**Comment by bjornmeansbear** [comment]
I moved the schedule to its own repo.
https://github.com/GD399-OSD/GD399-Schedule
